export const INCOMING_EVENTS = {
  ROOM_CREATED: ["room-created"],
  ROOM_SYNC: ["room-state", "reconnect-sync", "join_room", "room_state"],
  ROOM_LEFT: ["leave_room"],
  PLAYER_JOINED: ["player-joined", "player_joined"],
  BOT_JOINED: ["bot-joined"],
  BOTS_JOINED: ["bots-joined"],
  PLAYER_LEFT: ["player-left", "player_left"],
  OWNER_CHANGED: ["owner-changed"],
  PLAYER_KICKED: ["player-kicked"],
  START_GAME: ["game-start", "start_game", "start-game"],
  START_ROUND: ["start_round", "start-round"],
  SELECT_LETTER: ["select-letter", "select_letter"],
  NEW_LETTER: ["new-letter"],
  TIMER_UPDATE: ["timer-update", "update_timer"],
  INPUT_UPDATE: ["update-inputs", "update_inputs", "new-answer"],
  PRESS_STOP: ["press_stop"],
  ROUND_STOPPED: ["round-stopped", "round_stopped"],
  START_VOTING: ["start-voting", "start_voting"],
  SUBMIT_VOTE: ["submit_vote", "vote-update"],
  END_VOTING: ["end-voting", "end_voting"],
  VOTE_PROGRESS: ["vote-progress"],
  UPDATE_SCORES: ["update-scores", "update_scores"],
  ROUND_RESULTS: ["round-results"],
  NEXT_ROUND: ["next-round", "next_round"],
  READY_PROGRESS: ["ready-progress"],
  GAME_PAUSED: ["game-paused"],
  GAME_RESUMED: ["game-resumed"],
  PLAYER_RECONNECTED: ["player-reconnected"],
  GAME_FINISHED: ["game-finished", "game_finished", "game-end"],
  SOCKET_ERROR: ["error"]
};

export const OUTGOING_EVENTS = {
  CREATE_ROOM: "create-room",
  JOIN_ROOM: "join-room",
  LEAVE_ROOM: "leave-room",
  START_GAME: "start-game",
  PAUSE_GAME: "pause-game",
  RESUME_GAME: "resume-game",
  KICK_PLAYER: "kick-player",
  ADD_BOT: "add-bot",
  ADD_BOTS: "add-bots",
  RECONNECT_GAME: "reconnect-game",
  SELECT_LETTER: "select-letter",
  SUBMIT_ANSWER: "submit-answer",
  STOP_GAME: "stop-game",
  START_VOTING: "start-vote",
  SUBMIT_VOTE: "submit-vote",
  NEXT_ROUND: "next-round"
};
